name: Commitlint

on: [ push, pull_request ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check commit message
        uses: wagoid/commitlint-github-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configFile: .commitlintrc.json
