name: Cypress

on: [ pull_request ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Start application
        run: yarn start &
      - name: Run cypress
        run: yarn cypress-run

